### ISSUE TITLE
AttributeError during import on Python 3.6.3

### ISSUE THREAD

**Issue by ylemkimon** [HPAC/matchpy#28]
During import of the MatchPy on Python 3.6.3, following error occurs:
```
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matchpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\matchpy\__init__.py", line 5, in <module>
    from . import expressions
  File "C:\Python36\lib\site-packages\matchpy\expressions\__init__.py", line 4, in <module>
    from . import expressions
  File "C:\Python36\lib\site-packages\matchpy\expressions\expressions.py", line 225, in <module>
    class Arity(_ArityBase, Enum, metaclass=_ArityMeta):
  File "C:\Python36\lib\typing.py", line 977, in __new__
    self = super().__new__(cls, name, bases, namespace, _root=True)
  File "C:\Python36\lib\typing.py", line 137, in __new__
    return super().__new__(cls, name, bases, namespace)
  File "C:\Python36\lib\abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "C:\Python36\lib\enum.py", line 154, in __new__
    enum_class._member_names_ = []               # names in definition order
  File "C:\Python36\lib\typing.py", line 1177, in __setattr__
    super(GenericMeta, self._gorg).__setattr__(attr, value)
  File "C:\Python36\lib\enum.py", line 324, in __getattr__
    raise AttributeError(name) from None
AttributeError: _gorg
```

**Comment by Upabjojr** [comment]
Possibly related to a change in behaviour of _typing_ from Python 3.6.2 to 3.6.3

**Comment by wheerd** [comment]
I fixed it but accidentally gave the version the wrong name. And now PyPI seems to be down, so I cannot amend that right now. The version 4.4.1 is supposed to be 0.4.4...

**Comment by wheerd** [comment]
Nevermind, I fixed it.

**Comment by ylemkimon** [comment]
Thank you!
