### ISSUE TITLE
Cannot import matchpy

### ISSUE THREAD

**Issue by thom-popovici** [HPAC/matchpy#29]
>>> import matchpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "matchpy/__init__.py", line 5, in <module>
    from . import expressions
  File "matchpy/expressions/__init__.py", line 4, in <module>
    from . import expressions
  File "matchpy/expressions/expressions.py", line 90
    def variables(self) -> MultisetOfVariables:
                        ^
SyntaxError: invalid syntax

**Comment by wheerd** [comment]
Which version of Python are you using? Versions other than 3.5 and 3.6 are not supported.

**Comment by thom-popovici** [comment]
Hi.
I am using Python 2.7

**Comment by thom-popovici** [comment]
will try it with 3.5
