### ISSUE TITLE
Not Compatible with Python 3.7

### ISSUE THREAD

**Issue by saulshanabrook** [HPAC/matchpy#36]
```
Traceback (most recent call last):
  File "uarray.py", line 1, in <module>
    import matchpy
  File "/usr/local/miniconda3/envs/uarray/lib/python3.7/site-packages/matchpy/__init__.py", line 5, in <module>
    from . import expressions
  File "/usr/local/miniconda3/envs/uarray/lib/python3.7/site-packages/matchpy/expressions/__init__.py", line 4, in <module>
    from . import expressions
  File "/usr/local/miniconda3/envs/uarray/lib/python3.7/site-packages/matchpy/expressions/expressions.py", line 54, in <module>
    from typing import (Callable, Iterator, List, NamedTuple, Optional, Set, Tuple, TupleMeta, Type, Union)
ImportError: cannot import name 'TupleMeta' from 'typing' (/usr/local/miniconda3/envs/uarray/lib/python3.7/typing.py)
```

See https://github.com/RussBaz/enforce/issues/71 and https://github.com/ilevkivskyi/typing_inspect/blob/168fa6f7c5c55f720ce6282727211cf4cf6368f6/typing_inspect.py#L16-L24

**Comment by saulshanabrook** [comment]
Ah I see this was fixed in https://github.com/HPAC/matchpy/pull/34. Could you release a new version with this fix?

**Comment by henrik227** [comment]
I will as soon as possible.

**Comment by henrik227** [comment]
Done.

**Comment by saulshanabrook** [comment]
@henrik227 Thank you :)
