### ISSUE TITLE
Bug in ManyToOneReplacer

### ISSUE THREAD

**Issue by parsoyaarihant** [HPAC/matchpy#5]
Hi, I am receiving the following error while using `ManyToOneReplacer`. the same pattern is working properly with `replace_all`. 

I checked the `substitution` in `__call__` of `Constraint` and it is giving wrong `substitution` while using `ManyToOneReplacer`.

Substitution by `ManyToOneReplacer` is `{i2 ↦ x, i3 ↦ 3}` (`i2` and `i3` are not even in the variables).
Whereas Substitution by `replace_all` is `{m ↦ 3, x ↦ x}`

```python
>>> pattern2 = Pattern(Int(Pow(x_, m_), x_), cons(And(FreeQ(m_, x_), NonzeroQ(Add(ConstantSymbol(1), m_))), (m, x)))
>>> rule2 = ReplacementRule(pattern2, lambda m, x : Mul(Pow(Add(ConstantSymbol(1), m), ConstantSymbol(-1)), Pow(x, Add(ConstantSymbol(1), m))))
>>> subject = Int(Pow(x, ConstantSymbol(3)), x)
>>> replace_all(subject, [rule2])
Mul(Pow(Add(ConstantSymbol('1'), ConstantSymbol('3')), ConstantSymbol('-1')), Pow(VariableSymbol('x'), Add(ConstantSymbol('1'), ConstantSymbol('3'))))
>>> ManyToOneReplacer(rule2).replace(subject)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 754, in replace
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 89, in __iter__
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 137, in _match
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 147, in _match_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 276, in _match_regular_operation
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 179, in _check_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 137, in _match
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 147, in _match_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 276, in _match_regular_operation
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 179, in _check_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 137, in _match
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 159, in _match_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 179, in _check_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 137, in _match
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 159, in _match_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 175, in _check_transition
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.3.1-py3.6.egg/matchpy/matching/many_to_one.py", line 205, in _check_constraints
  File "/Users/parsoyaarihant/sympy/sympy/rubi/constraint.py", line 13, in __call__
    return sympify(str(substitute(self.expr, substitution)))
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/sympy/core/sympify.py", line 322, in sympify
    expr = parse_expr(a, local_dict=locals, transformations=transformations, evaluate=evaluate)
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
TypeError: 'Symbol' object is not subscriptable
```

**Comment by parsoyaarihant** [comment]
Here is my `Constraint` function (`cons()`):

``` python
from matchpy import Constraint, substitute
from sympy import sympify

class cons(Constraint):
    def __init__(self, expr, vars):
        self.expr = expr
        self.vars = frozenset(v.name for v in vars)

    def __call__(self, substitution):
        sub = substitute(self.expr, substitution)
        try:
            return sympify(str(sub))
        except:
            print(('Unable to sympify: {}').format(sub))
            return False

    @property
    def variables(self):
        return self.vars

    def with_renamed_vars(self, renaming):
        copy = cons(self.expr, [])
        copy.vars = frozenset(renaming.get(v, v) for v in self.vars)
        return copy

    def __eq__(self, other):
        return isinstance(other, cons) and other.vars == self.vars and other.expr == self.expr

    def __hash__(self):
        return hash((self.vars, self.expr))
```

I figured out that `self.vars` are getting changed in `with_renamed_vars` from `frozenset({'m', 'x'})` to `frozenset({'i1', 'i2'})` and stays the same when `__call__` is called.

**Comment by wheerd** [comment]
You will have to rename the variables in the expression as well:

```python
    def with_renamed_vars(self, renaming):
        new_expr = self.expr.with_renamed_vars(renaming)
        new_vars = [renaming.get(v, v) for v in self.vars]
        return cons(new_expr, new_vars)
```

Unfortunately, this will only work if the expression consists of `Expression` instances, i.e. no `int`s etc. I want to get rid of the requirement for renaming. I hope I can get to that next week, but I can't promise it.

**Comment by parsoyaarihant** [comment]
Thanks!
